package main

import (
	"fmt"
	"strings"

	"github.com/jhonsferg/traverse"
)

// Generator handles OData metadata to Go code generation.
type Generator struct {
	metadata *traverse.Metadata
	pkgName  string
}

// NewGenerator creates a new code generator.
func NewGenerator(metadata *traverse.Metadata, pkgName string) *Generator {
	return &Generator{
		metadata: metadata,
		pkgName:  pkgName,
	}
}

// ODataTypeMapping maps OData types to Go types.
var ODataTypeMapping = map[string]string{
	"Edm.String":         "string",
	"Edm.Int32":          "int32",
	"Edm.Int64":          "int64",
	"Edm.Boolean":        "bool",
	"Edm.Decimal":        "*big.Rat",
	"Edm.Single":         "float32",
	"Edm.Double":         "float64",
	"Edm.DateTime":       "traverse.DateTime",
	"Edm.DateTimeOffset": "traverse.DateTimeOffset",
	"Edm.Time":           "time.Time",
	"Edm.Date":           "time.Time",
	"Edm.Guid":           "traverse.Guid",
	"Edm.Byte":           "byte",
	"Edm.Binary":         "[]byte",
	"Edm.SByte":          "int8",
}

// MapODataType maps an OData type string to a Go type.
// Returns the Go type and a boolean indicating if it's a pointer type (for nullable fields).
func MapODataType(odataType string, nullable bool) (string, bool) {
	// Remove "Collection(...)" wrapper if present
	if strings.HasPrefix(odataType, "Collection(") {
		odataType = strings.TrimPrefix(odataType, "Collection(")
		odataType = strings.TrimSuffix(odataType, ")")
		// Handle collections (for now, return slice of type)
		baseType, _ := MapODataType(odataType, nullable)
		return "[]" + baseType, false
	}

	// Check if it's a built-in Edm type
	if goType, ok := ODataTypeMapping[odataType]; ok {
		// Determine if type should be a pointer
		isPointer := nullable && !isBasicScalarType(goType)
		if isPointer {
			return "*" + goType, true
		}
		return goType, false
	}

	// Assume it's a complex type or entity
	return odataType, nullable
}

// isBasicScalarType checks if a Go type is a basic scalar (not a pointer-compatible type).
func isBasicScalarType(goType string) bool {
	basicTypes := map[string]bool{
		"string":  true,
		"int32":   true,
		"int64":   true,
		"bool":    true,
		"float32": true,
		"float64": true,
		"byte":    true,
		"int8":    true,
	}
	return basicTypes[goType]
}

// GenerateTypes generates the types.go file with entity struct definitions.
func (g *Generator) GenerateTypes() string {
	var buf strings.Builder

	// Write package and imports
	buf.WriteString("// Code generated by traverse-gen. DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", g.pkgName)
	buf.WriteString("import (\n")
	buf.WriteString("\t\"big\"\n")
	buf.WriteString("\t\"time\"\n")
	buf.WriteString("\t\"github.com/jhonsferg/traverse\"\n")
	buf.WriteString(")\n\n")

	// Generate entity types
	for _, et := range g.metadata.EntityTypes {
		buf.WriteString(generateEntityStruct(et))
		buf.WriteString("\n")
	}

	return buf.String()
}

// generateEntityStruct generates a struct definition for an entity type.
func generateEntityStruct(et traverse.EntityType) string {
	var buf strings.Builder

	// Generate struct comment
	fmt.Fprintf(&buf, "// %s represents an OData %s entity.\n", pascalCase(et.Name), et.Name)
	fmt.Fprintf(&buf, "type %s struct {\n", pascalCase(et.Name))

	// Generate fields for properties
	for _, prop := range et.Properties {
		goType, _ := MapODataType(prop.Type, prop.Nullable)

		// Format field name
		fieldName := pascalCase(prop.Name)

		// Check if this is a key field
		isKey := isKeyField(et, prop.Name)

		// Generate struct tag
		tag := generateStructTag(prop.Name, isKey)

		fmt.Fprintf(&buf, "\t%s %s %s\n", fieldName, goType, tag)
	}

	// Generate navigation property fields as pointers to slices or single entities
	for _, navProp := range et.NavigationProperties {
		fieldName := pascalCase(navProp.Name)
		// For now, represent navigation properties as []*EntityType or *EntityType
		// More sophisticated logic could use the multiplicity information
		fmt.Fprintf(&buf, "\t// Navigation property: %s\n", navProp.Name)
		fmt.Fprintf(&buf, "\t%s []*%s `json:\"%s,omitempty\"`\n", fieldName, fieldName, navProp.Name)
	}

	buf.WriteString("}\n")

	return buf.String()
}

// isKeyField checks if a property is a key field.
func isKeyField(et traverse.EntityType, propName string) bool {
	for _, keyRef := range et.Key {
		if keyRef.Name == propName {
			return true
		}
	}
	return false
}

// generateStructTag generates a struct tag for JSON marshaling.
func generateStructTag(propName string, isKey bool) string {
	tag := fmt.Sprintf("`json:\"%s\"", propName)

	// Add omitempty for nullable fields
	tag += ",omitempty`"

	return tag
}

// pascalCase converts snake_case or space-separated strings to PascalCase.
func pascalCase(s string) string {
	// Handle special characters and spaces
	s = strings.TrimSpace(s)
	parts := strings.FieldsFunc(s, func(r rune) bool {
		return r == '_' || r == ' ' || r == '-'
	})

	for i, part := range parts {
		if len(part) > 0 {
			parts[i] = strings.ToUpper(string(part[0])) + strings.ToLower(part[1:])
		}
	}

	return strings.Join(parts, "")
}

// GenerateClient generates the client.go file with client wrapper.
func (g *Generator) GenerateClient() string {
	var buf strings.Builder

	buf.WriteString("// Code generated by traverse-gen. DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", g.pkgName)
	buf.WriteString("import (\n")
	buf.WriteString("\t\"context\"\n")
	buf.WriteString("\t\"github.com/jhonsferg/traverse\"\n")
	buf.WriteString(")\n\n")

	buf.WriteString("// Client wraps traverse.Client with type-safe methods.\n")
	buf.WriteString("type Client struct {\n")
	buf.WriteString("\t*traverse.Client\n")
	buf.WriteString("}\n\n")

	buf.WriteString("// NewClient creates a new typed client.\n")
	buf.WriteString("func NewClient(c *traverse.Client) *Client {\n")
	buf.WriteString("\treturn &Client{Client: c}\n")
	buf.WriteString("}\n\n")

	// Generate entity set accessors
	for _, es := range g.metadata.EntitySets {
		buf.WriteString(generateEntitySetAccessor(es))
		buf.WriteString("\n")
	}

	return buf.String()
}

// generateEntitySetAccessor generates a method to access an entity set.
func generateEntitySetAccessor(es traverse.EntitySetInfo) string {
	var buf strings.Builder

	methodName := pascalCase(es.Name)
	fmt.Fprintf(&buf, "// %s returns a query builder for the %s entity set.\n", methodName, es.Name)
	fmt.Fprintf(&buf, "func (c *Client) %s() *traverse.QueryBuilder {\n", methodName)
	fmt.Fprintf(&buf, "\treturn c.Client.Query(\"%s\")\n", es.Name)
	buf.WriteString("}\n")

	return buf.String()
}

// GenerateQueries generates the queries.go file with query builders and CRUD methods.
func (g *Generator) GenerateQueries() string {
	var buf strings.Builder

	buf.WriteString("// Code generated by traverse-gen. DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", g.pkgName)
	buf.WriteString("import (\n")
	buf.WriteString("\t\"context\"\n")
	buf.WriteString("\t\"fmt\"\n")
	buf.WriteString("\t\"github.com/jhonsferg/traverse\"\n")
	buf.WriteString(")\n\n")

	// Generate query builder types for each entity
	for _, et := range g.metadata.EntityTypes {
		buf.WriteString(generateQueryBuilder(et))
		buf.WriteString("\n")
	}

	return buf.String()
}

// generateQueryBuilder generates query builder methods for an entity type.
func generateQueryBuilder(et traverse.EntityType) string {
	var buf strings.Builder

	typeName := pascalCase(et.Name)
	queryName := typeName + "Query"

	// Query builder type
	fmt.Fprintf(&buf, "// %s is a query builder for %s entities.\n", queryName, typeName)
	fmt.Fprintf(&buf, "type %s struct {\n", queryName)
	buf.WriteString("\tqb *traverse.QueryBuilder\n")
	buf.WriteString("}\n\n")

	// GetKey method to retrieve entity by key
	if len(et.Key) > 0 {
		_ = et.Key[0].Name
		fmt.Fprintf(&buf, "// GetByKey retrieves a single %s by key.\n", typeName)
		fmt.Fprintf(&buf, "func (q *%s) GetByKey(ctx context.Context, key interface{}) (*%s, error) {\n", queryName, typeName)
		fmt.Fprintf(&buf, "\tvar result %s\n", typeName)
		fmt.Fprintf(&buf, "\tif err := q.qb.Key(fmt.Sprintf(\"%%v\", key)).GetOne(ctx, &result); err != nil {\n")
		buf.WriteString("\t\treturn nil, err\n")
		buf.WriteString("\t}\n")
		buf.WriteString("\treturn &result, nil\n")
		buf.WriteString("}\n\n")
	}

	// GetAll method
	fmt.Fprintf(&buf, "// GetAll retrieves all %s entities.\n", typeName)
	fmt.Fprintf(&buf, "func (q *%s) GetAll(ctx context.Context) ([]*%s, error) {\n", queryName, typeName)
	fmt.Fprintf(&buf, "\tvar results []*%s\n", typeName)
	buf.WriteString("\tif err := q.qb.GetMultiple(ctx, &results); err != nil {\n")
	buf.WriteString("\t\treturn nil, err\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\treturn results, nil\n")
	buf.WriteString("}\n\n")

	// Filter method
	buf.WriteString("// Filter adds a filter expression to the query.\n")
	fmt.Fprintf(&buf, "func (q *%s) Filter(expr string) *%s {\n", queryName, queryName)
	buf.WriteString("\tq.qb = q.qb.Filter(expr)\n")
	buf.WriteString("\treturn q\n")
	buf.WriteString("}\n\n")

	// Select method
	buf.WriteString("// Select specifies which fields to return.\n")
	fmt.Fprintf(&buf, "func (q *%s) Select(fields ...string) *%s {\n", queryName, queryName)
	buf.WriteString("\tq.qb = q.qb.Select(fields...)\n")
	buf.WriteString("\treturn q\n")
	buf.WriteString("}\n\n")

	// OrderBy method
	buf.WriteString("// OrderBy adds an order by clause.\n")
	fmt.Fprintf(&buf, "func (q *%s) OrderBy(expr string) *%s {\n", queryName, queryName)
	buf.WriteString("\tq.qb = q.qb.OrderBy(expr)\n")
	buf.WriteString("\treturn q\n")
	buf.WriteString("}\n\n")

	// Skip method
	buf.WriteString("// Skip skips the specified number of entities.\n")
	fmt.Fprintf(&buf, "func (q *%s) Skip(count int) *%s {\n", queryName, queryName)
	buf.WriteString("\tq.qb = q.qb.Skip(int64(count))\n")
	buf.WriteString("\treturn q\n")
	buf.WriteString("}\n\n")

	// Top method
	buf.WriteString("// Top limits the number of entities returned.\n")
	fmt.Fprintf(&buf, "func (q *%s) Top(count int) *%s {\n", queryName, queryName)
	buf.WriteString("\tq.qb = q.qb.Top(int64(count))\n")
	buf.WriteString("\treturn q\n")
	buf.WriteString("}\n\n")

	return buf.String()
}
