package main

import (
	"text/template"
)

// TemplateRegistry holds the text/template instances for each generated file.
type TemplateRegistry struct {
	typesTemplate   *template.Template
	clientTemplate  *template.Template
	queriesTemplate *template.Template
}

// NewTemplateRegistry creates a TemplateRegistry with the default built-in templates.
func NewTemplateRegistry() *TemplateRegistry {
	return &TemplateRegistry{
		typesTemplate:   template.Must(template.New("types").Parse(defaultTypesTemplate)),
		clientTemplate:  template.Must(template.New("client").Parse(defaultClientTemplate)),
		queriesTemplate: template.Must(template.New("queries").Parse(defaultQueriesTemplate)),
	}
}

// SetTypesTemplate replaces the types.go template.
func (tr *TemplateRegistry) SetTypesTemplate(tmpl *template.Template) { tr.typesTemplate = tmpl }

// SetClientTemplate replaces the client.go template.
func (tr *TemplateRegistry) SetClientTemplate(tmpl *template.Template) { tr.clientTemplate = tmpl }

// SetQueriesTemplate replaces the queries.go template.
func (tr *TemplateRegistry) SetQueriesTemplate(tmpl *template.Template) {
	tr.queriesTemplate = tmpl
}

// TypesTemplateData is passed to the types.go template.
type TypesTemplateData struct {
	PackageName         string
	NeedsTimeImport     bool
	NeedsTraverseImport bool
	Entities            []EntityData
	ComplexTypes        []ComplexTypeData
	EnumTypes           []EnumTypeData
}

// EntityData describes a single OData EntityType for templating.
type EntityData struct {
	Name     string
	GoName   string
	Fields   []FieldData
	NavProps []NavPropData
}

// FieldData describes one property field in an entity or complex type.
type FieldData struct {
	Name       string
	GoName     string
	GoType     string
	IsKey      bool
	IsNullable bool
	Tag        string
}

// NavPropData describes one navigation property.
type NavPropData struct {
	Name   string
	GoName string
	GoType string
	Tag    string
}

// ComplexTypeData describes an OData ComplexType.
type ComplexTypeData struct {
	Name   string
	GoName string
	Fields []FieldData
}

// EnumTypeData describes an OData EnumType.
type EnumTypeData struct {
	Name    string
	GoName  string
	Members []EnumMemberData
}

// EnumMemberData describes one member of an OData EnumType.
type EnumMemberData struct {
	Name   string
	GoName string
	Value  string
}

// ClientTemplateData is passed to the client.go template.
type ClientTemplateData struct {
	PackageName string
	EntitySets  []EntitySetData
}

// EntitySetData describes one OData EntitySet for client.go templating.
type EntitySetData struct {
	Name       string
	GoName     string
	EntityType string
	QueryType  string
}

// QueriesTemplateData is passed to the queries.go template.
type QueriesTemplateData struct {
	PackageName   string
	QueryBuilders []QueryBuilderData
}

// QueryBuilderData describes one typed query builder for queries.go.
type QueryBuilderData struct {
	Name       string
	GoName     string
	QueryType  string
	EntityType string
}

// defaultTypesTemplate is the built-in template for types.go.
const defaultTypesTemplate = `// Code generated by traverse-gen. DO NOT EDIT.

package {{.PackageName}}

import ({{if .NeedsTimeImport}}
"time"
{{end}}{{if .NeedsTraverseImport}}
"github.com/jhonsferg/traverse"
{{end}})
{{range .Entities}}
// {{.GoName}} is an OData entity type.
type {{.GoName}} struct {
{{range .Fields}}{{.GoName}} {{.GoType}} {{.Tag}}
{{end}}{{range .NavProps}}{{.GoName}} {{.GoType}} {{.Tag}}
{{end}}}
{{end}}
{{range .ComplexTypes}}
// {{.GoName}} is an OData complex type.
type {{.GoName}} struct {
{{range .Fields}}{{.GoName}} {{.GoType}} {{.Tag}}
{{end}}}
{{end}}
{{range .EnumTypes}}
// {{.GoName}} is an OData enum type.
type {{.GoName}} string

const (
{{range .Members}}{{$.GoName}}{{.GoName}} {{$.GoName}} = "{{.Name}}"
{{end}})
{{end}}`

// defaultClientTemplate is the built-in template for client.go.
const defaultClientTemplate = `// Code generated by traverse-gen. DO NOT EDIT.

package {{.PackageName}}

import "github.com/jhonsferg/traverse"

// GeneratedClient wraps traverse.Client with typed entity set accessors.
type GeneratedClient struct {
*traverse.Client
}

// NewGeneratedClient creates a new GeneratedClient for the given base URL.
func NewGeneratedClient(baseURL string, opts ...traverse.Option) (*GeneratedClient, error) {
opts = append([]traverse.Option{traverse.WithBaseURL(baseURL)}, opts...)
c, err := traverse.New(opts...)
if err != nil {
return nil, err
}
return &GeneratedClient{Client: c}, nil
}
{{range .EntitySets}}
// {{.GoName}} returns a typed query builder for the {{.Name}} entity set.
func (c *GeneratedClient) {{.GoName}}() *{{.QueryType}} {
return &{{.QueryType}}{QueryBuilder: c.Client.From("{{.Name}}")}
}
{{end}}`

// defaultQueriesTemplate is the built-in template for queries.go.
const defaultQueriesTemplate = `// Code generated by traverse-gen. DO NOT EDIT.

package {{.PackageName}}

import "github.com/jhonsferg/traverse"
{{range .QueryBuilders}}
// {{.QueryType}} builds OData queries for the {{.Name}} entity set.
type {{.QueryType}} struct {
*traverse.QueryBuilder
}
{{end}}`
