package main

import (
	"text/template"
)

// TemplateRegistry holds customizable code generation templates.
type TemplateRegistry struct {
	typesTemplate   *template.Template
	clientTemplate  *template.Template
	queriesTemplate *template.Template
}

// TypesTemplateData contains data for the types.go template.
type TypesTemplateData struct {
	PackageName string
	Entities    []EntityData
}

// EntityData represents entity information for templating.
type EntityData struct {
	Name     string
	GoName   string
	Fields   []FieldData
	NavProps []NavPropData
	Keys     []string
}

// FieldData represents a field in an entity struct.
type FieldData struct {
	Name        string
	GoName      string
	Type        string
	IsKey       bool
	IsNullable  bool
	JSONTag     string
	Description string
}

// NavPropData represents a navigation property.
type NavPropData struct {
	Name       string
	GoName     string
	JSONTag    string
	TargetType string
	IsSingle   bool
}

// ClientTemplateData contains data for the client.go template.
type ClientTemplateData struct {
	PackageName string
	EntitySets  []EntitySetData
}

// EntitySetData represents an entity set for templating.
type EntitySetData struct {
	Name       string
	GoName     string
	EntityName string
}

// QueryTemplateData contains data for the queries.go template.
type QueryTemplateData struct {
	PackageName   string
	QueryBuilders []QueryBuilderData
}

// QueryBuilderData represents a query builder for templating.
type QueryBuilderData struct {
	EntityName   string
	EntityGoName string
	QueryName    string
	Keys         []string
	HasKeyAccess bool
}

// NewTemplateRegistry creates a new template registry with default templates.
func NewTemplateRegistry() *TemplateRegistry {
	return &TemplateRegistry{
		typesTemplate:   template.Must(template.New("types").Parse(defaultTypesTemplate())),
		clientTemplate:  template.Must(template.New("client").Parse(defaultClientTemplate())),
		queriesTemplate: template.Must(template.New("queries").Parse(defaultQueriesTemplate())),
	}
}

// SetTypesTemplate sets a custom template for types.go generation.
func (tr *TemplateRegistry) SetTypesTemplate(tmpl *template.Template) {
	tr.typesTemplate = tmpl
}

// SetClientTemplate sets a custom template for client.go generation.
func (tr *TemplateRegistry) SetClientTemplate(tmpl *template.Template) {
	tr.clientTemplate = tmpl
}

// SetQueriesTemplate sets a custom template for queries.go generation.
func (tr *TemplateRegistry) SetQueriesTemplate(tmpl *template.Template) {
	tr.queriesTemplate = tmpl
}

// defaultTypesTemplate returns the default template for types.go.
func defaultTypesTemplate() string {
	return `// Code generated by traverse-gen. DO NOT EDIT.

package {{ .PackageName }}

import (
	"math/big"
	"time"
	"github.com/jhonsferg/traverse"
)

{{ range .Entities }}
// {{ .GoName }} represents an OData {{ .Name }} entity.
type {{ .GoName }} struct {
{{ range .Fields }}
	// {{ .GoName }}{{ if .Description }} - {{ .Description }}{{ end }}
	{{ .GoName }} {{ .Type }} {{ .JSONTag }}
{{ end }}
{{ range .NavProps }}
	// {{ .GoName }} navigation property
	{{ .GoName }} []*{{ .TargetType }} {{ .JSONTag }}
{{ end }}
}

{{ end }}
`
}

// defaultClientTemplate returns the default template for client.go.
func defaultClientTemplate() string {
	return `// Code generated by traverse-gen. DO NOT EDIT.

package {{ .PackageName }}

import (
	"github.com/jhonsferg/traverse"
)

// Client wraps traverse.Client with type-safe methods.
type Client struct {
	*traverse.Client
}

// NewClient creates a new typed client.
func NewClient(c *traverse.Client) *Client {
	return &Client{Client: c}
}

{{ range .EntitySets }}
// {{ .GoName }} returns a query builder for the {{ .Name }} entity set.
func (c *Client) {{ .GoName }}() *traverse.QueryBuilder {
	return c.Client.Query("{{ .Name }}")
}
{{ end }}
`
}

// defaultQueriesTemplate returns the default template for queries.go.
func defaultQueriesTemplate() string {
	return `// Code generated by traverse-gen. DO NOT EDIT.

package {{ .PackageName }}

import (
	"context"
	"fmt"
	"github.com/jhonsferg/traverse"
)

{{ range .QueryBuilders }}
// {{ .QueryName }} is a query builder for {{ .EntityGoName }} entities.
type {{ .QueryName }} struct {
	qb *traverse.QueryBuilder
}

// GetAll retrieves all {{ .EntityGoName }} entities.
func (q *{{ .QueryName }}) GetAll(ctx context.Context) ([]*{{ .EntityGoName }}, error) {
	var results []*{{ .EntityGoName }}
	if err := q.qb.GetMultiple(ctx, &results); err != nil {
		return nil, err
	}
	return results, nil
}

// Filter adds a filter expression to the query.
func (q *{{ .QueryName }}) Filter(expr string) *{{ .QueryName }} {
	q.qb = q.qb.Filter(expr)
	return q
}

// Select specifies which fields to return.
func (q *{{ .QueryName }}) Select(fields ...string) *{{ .QueryName }} {
	q.qb = q.qb.Select(fields...)
	return q
}

// OrderBy adds an order by clause.
func (q *{{ .QueryName }}) OrderBy(expr string) *{{ .QueryName }} {
	q.qb = q.qb.OrderBy(expr)
	return q
}

// Skip skips the specified number of entities.
func (q *{{ .QueryName }}) Skip(count int) *{{ .QueryName }} {
	q.qb = q.qb.Skip(int64(count))
	return q
}

// Top limits the number of entities returned.
func (q *{{ .QueryName }}) Top(count int) *{{ .QueryName }} {
	q.qb = q.qb.Top(int64(count))
	return q
}

{{ if .HasKeyAccess }}
// GetByKey retrieves a single {{ .EntityGoName }} by key.
func (q *{{ .QueryName }}) GetByKey(ctx context.Context, key interface{}) (*{{ .EntityGoName }}, error) {
	var result {{ .EntityGoName }}
	if err := q.qb.Key(fmt.Sprintf("%v", key)).GetOne(ctx, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
{{ end }}

{{ end }}
`
}
